version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    container_name: api

  frontend:
    build:
      context: ./frontend
    ports: 
      - "80:80"
    container_name: frontend
    stdin_open: true